language: php
matrix:
  fast_finish: true
  include:
  - php: 7.1
  - php: 7.2
  - php: 7.3
  - php: 7.4
  - php: 8.0
  - php: nightly
  allow_failures:
  - php: nightly
before_install:
- travis_retry composer install --no-interaction --ignore-platform-reqs
script:
- ./vendor/bin/phpunit
